### ISSUE TITLE
Losing records from Measurements - > Lab results cm

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#109]
reasons 
- measurement_conept_id =0 
- operator_concept_id = 0 
- labs not in the PCORnet list

**Comment by toanong** [comment]
1) even if the records get to PCORnet CDM, it won't be queried.
3) if the labs are not in PCORnet list, is there a reason why we want to move them forward?

2) The records got dropped because of this JOIN:
	join vocabulary.concept c2 on m.operator_concept_id = c2.concept_id and c2.domain_id = 'Meas Value Operator'

Since the RESULT_MODIFIER is not a required field in the LAB_RESULT_CM table, we can make it a LEFT JOIN.
