### ISSUE TITLE
create (start2001) ETL scripts 

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#132]
Please create a new folder called `start2001` or something similar, and copy all ETL scripts.  In each ETL script, we need to add a clause to only draw patients or visits from `person_visit_start2001` table.

**Comment by piglet25** [comment]
Finished converting ETL scripts for chop and dcc to only draw patients or visits from person_visit_start2001. I only run up to chop encounter because db01 was down for maintenance starting at 6pm Friday until 6am Monday and today (Monday) Dave renamed v24 to v24 temp because of major problems with merge. I will run these when the problems on db01 are corrected.

**Comment by writetoritu** [comment]
@piglet25 the scripts are looking good to me. My only comment is that `chop_start2001_pcornet.cz_omop_pcornet_concept_map` should be same as `dcc_pcornet.cz_omop_pcornet_concept_map` (you could use either in the queries). 

Let us resume the testing on `chop_start2001_pcornet` schema.
