### ISSUE TITLE
Review pcornet implementation guidelines 3.1

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#325]
Align the code as per the guidelines

add link - http://pcornet.org/wp-content/uploads/2017/05/2017-05-01_Integrated-CDM-Specification-Implemeantion-Guidance-CDM-v....pdf

**Comment by ChavanShweta** [comment]
fixes #325
Following Implementation Guidelines are been added in the document:
- [ ] 1. If performing the Date Obfuscation and/or Truncation - Future date shifts are discouraged. Only backwards shift could be applied.
- [ ] 2. Precision/scale from RDBMS Numbers field is being deprecated 
- [ ] 3. Enrollment table: If the patient has both medical and drug coverage, each form of coverage would have a separate records. 
  `  The enrollment table script it is by default to 'E' i.e. Encounter based is this because we don't have any insurance coverage related data from the data marts. There are following predefined valusets:`
`I = Medical insurance coverage`
`D = Outpatient prescription drug coverage`
`G = geography`
`A = algorithmic`
`E = Encounter-Based`
- [ ] 4. New valueset added in the enc_type that is not in the valueset map `IC = Institutional Professional Consult(permissible substitution)`
- [ ] 5. Table: Diagnosis - `dx_origin is null throughput the table. The scripts specifies it should be OT if null`
- [ ] 6. Table: Procedures - valueset should be modified to combine the CPT and HCPCS codes into one category
- [ ] 7. Table: Lab_result_cm - valueset updated to incorporate the null value options as:
    `NI = No Information`
      `UN = Unknown`
      `OT = Other`
    -` Column: result_num data type modified to numeric(15,8) `- we have it numeric(25,8)
- [ ] 8. Table: Condition -  value set needs to be updated to reference both clinical modification(CM) and procedure coding (PCS)
- [ ] 9. Table: Prescribing - `column: rx_quantity number precision and scale updated to numeric(15,8) - we are using numeric(20,2)`
     `PI = Pill`
       `TA = Tablet`
       `VI = vial`
       `LI = liquid`
      `SO = Solution`
     ` SU = Suspension`
      `OI = Ointment`
      `CR = Cream`
      `PO = Powder`
     ` PA = Patch`
     ` IN = Inhaler`
     `KI = Kit`
     `DE = Device`
     `NI = No information`
     `UN = Unknown`
     `OT = Other`
     -`column: rx_refills number precision and scale updated to numeric(15,8) - we are using numeric(20,2)`
    -`column: rx_days_supply number precision and scale updated to numeric(15,8) - we are using numeric(20,2)`
   -`column: rx_basis - The valueset items updated and the field definition`
      `01 = Order to Dispense`
      `02 = Order to administer`

**Comment by writetoritu** [comment]
@ChavanShweta Could you please elaborate on the 5th point? `5. Table: Diagnosis - dx_origin is null throughput the table. The scripts specifies it should be OT if null`

**Comment by writetoritu** [comment]
action item 
- [ ] add `09=ICD-9-CM/PCS, 10=ICD-10-CM/PCS, 11=ICD-11-CM/PCS` mapping to condition type domain
