### ISSUE TITLE
update harvest table data 

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#359]
with the pedsnet cycle refresh date

**Comment by ChavanShweta** [comment]
Harvest table was updated with as i updated the code

**Comment by writetoritu** [comment]
create a parameter in the config file to store the `pedsnet cycle date` and copy this value over to various date table in the harvest table

**Comment by ChavanShweta** [comment]
This issue is fixed. The code is updated with harvest data refresh. Branch fixed-issue-364

To refresh the Harvest refresh date use following command

`loading  -h <host_name> -u <user_name> -d <database_name> -s <schema_name> -H <refresh_date> -o etl`

> Example :   loading  -h host.edu -u shweta -d db_test -s test_schema -H 2017-12-15 -o etl

Note: the harvest refresh date is kept as optional parameter as it changes once over pedsnet cycle. Once updated its not necessary to change for ever etl run for pedsnet cycle.
