### ISSUE TITLE
Lab_result_cm.result_loc

### ISSUE THREAD

**Issue by writetoritu** [PEDSnet/pedsnetcdm_to_pcornetcdm#39]
how to populate result_loc ? 
It's not in the measurement table ... to be discussed with leadership

**Comment by mgkahn** [comment]
This is another instance of where if we decide to expand our ETL to include this in OMOP (my vote), I strongly recommend expanding the measurement table than trying to stick into observation and link using fact_relation.

For current ETL, we need to set to UN because, given our current ETL specs, we don't know anything about location. If we agree to include in expanded PEDSnet model, then in our upcoming next round, we have folks expand their ETL to include as new field in Measurement (if folks agree with expanding Measurement with result_loc).

**Comment by burrowse** [comment]
Adding this to the DM agenda for Thursday, we aimed to release the complete 2.1 spec by next monday so this needs to be included before it goes out.

**Comment by writetoritu** [comment]
Thanks @mgkahn - for v2->v3 transform, we will use 'UN' until we have a decision for https://github.com/PEDSnet/Data_Models/issues/182

**Comment by writetoritu** [comment]
revisiting.,,,,

Sites wont be able to distinguish between POC and L in the ongoing ETL cycle. 
One way to distinguish is the use of 'POC' and 'POCT' in the lab values (or other conventions used by the sites). The transformation will try to use this information to populate result_loc,
